import React, { useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import AOS from 'aos';
import 'aos/dist/aos.css';
import '../../../App.css';
import NavbarCustom from '../includes/NavbarCustom';

export default function TermsOfUse() {
    useEffect(() => {
        AOS.init({ duration: 800, once: true });
    }, []);

    return (
        <>
            <NavbarCustom />
            <div className="container py-5" style={{ maxWidth: 860 }} data-aos="fade-up">
                <h1 className="fw-bold mb-2">Terms of Use</h1>
                <p className="text-muted mb-4">Last updated: <em>[Insert Date]</em></p>

                <div className="alert alert-warning small">
                    <i className="bi bi-exclamation-triangle me-2" />
                    This document contains placeholders (in brackets) to be completed by Utsavam's
                    operating organization and reviewed by qualified legal counsel before publication.
                </div>

                <h2 className="h5 fw-bold mt-4">1. Acceptance of Terms</h2>
                <p>
                    By creating an account or otherwise using Utsavam ("the Platform"), you agree to
                    these Terms of Use and to our <a href="/privacy-policy">Privacy Policy</a>. If you do
                    not agree, please do not use the Platform.
                </p>

                <h2 className="h5 fw-bold mt-4">2. Who May Use the Platform</h2>
                <p>
                    The Platform is intended for use by Event Organizers (Mandal administrators),
                    Donation Collectors, and platform staff acting on behalf of a registered
                    organization. Donors interact with the Platform indirectly, through a Donation
                    Collector, and are covered by the consent and privacy terms described in our
                    Privacy Policy rather than by creating an account of their own.
                </p>

                <h2 className="h5 fw-bold mt-4">3. Accurate Information</h2>
                <p>
                    You agree to provide accurate registration information and to keep it up to date.
                    When entering donor information on a donor's behalf, you confirm that the donor has
                    been informed of how their information will be used, consistent with our donor
                    consent requirements.
                </p>

                <h2 className="h5 fw-bold mt-4">4. Responsible Use</h2>
                <p>You agree not to:</p>
                <ul>
                    <li>Use the Platform to submit false donation, donor, or expense records.</li>
                    <li>Attempt to access accounts, events, or data you are not authorized to access.</li>
                    <li>Misuse receipt identifiers or QR codes, including sharing another person's receipt as your own.</li>
                    <li>Interfere with the security or normal operation of the Platform.</li>
                </ul>

                <h2 className="h5 fw-bold mt-4">5. Receipts</h2>
                <p>
                    Digital receipts are generated by the Platform based on donation records entered by
                    a Donation Collector. A receipt is a record of a specific donation and does not, by
                    itself, constitute independent proof of a donor's identity.
                </p>

                <h2 className="h5 fw-bold mt-4">6. Account Responsibility</h2>
                <p>
                    You are responsible for maintaining the confidentiality of your login credentials
                    and for all activity under your account. Notify us immediately at{' '}
                    <strong>[Insert Contact Email]</strong> if you suspect unauthorized use.
                </p>

                <h2 className="h5 fw-bold mt-4">7. Suspension and Termination</h2>
                <p>
                    We may suspend or terminate access to the Platform for accounts that violate these
                    Terms, at the discretion of <strong>[Insert Legal Entity Name]</strong>.
                </p>

                <h2 className="h5 fw-bold mt-4">8. Disclaimer</h2>
                <p>
                    The Platform is provided "as is." <strong>[Insert applicable warranty/liability
                    disclaimers once reviewed by legal counsel.]</strong>
                </p>

                <h2 className="h5 fw-bold mt-4">9. Changes to These Terms</h2>
                <p>We may update these Terms from time to time. Continued use of the Platform after changes constitutes acceptance of the updated Terms.</p>

                <h2 className="h5 fw-bold mt-4">10. Contact Us</h2>
                <p>Questions about these Terms can be sent to <strong>[Insert Contact Email]</strong>.</p>
            </div>
        </>
    );
}
